print("----------------------")
userName = input("Enter your name: ")
userAge = input("Enter your age: ")
userColor = input("Enter your favorite color: ")
userFood = input("Enter your favorite food: ")
print("----------------------")
print("===== My Profile =====")
print(f"Name: {userName}")
print(f"Age: {userAge}")
print(f"Favorite color: {userColor}")
print(f"Favorite food: {userFood}")